// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIService talks to OpenAI-compatible chat-completion endpoints.
 * Cloud: DeepSeek / OpenAI / Qwen / Kimi / GLM / Doubao / custom.
 * Local: the common desktop OpenAI-compatible servers, plus a generic CLI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelChat aborts a streaming request previously started with Chat.
 */
export function CancelChat(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(2361739144, requestID);
}

/**
 * Chat streams a completion; deltas arrive as "ai-stream" events tagged with
 * requestID, and the final full text is returned.
 */
export function Chat(requestID: string, messages: $models.ChatMessage[] | null, temperature: number): $CancellablePromise<string> {
    return $Call.ByID(420759634, requestID, messages, temperature);
}

/**
 * DeleteProfile removes a profile; if the active one goes, the first
 * remaining profile takes over.
 */
export function DeleteProfile(id: string): $CancellablePromise<$models.AIProfileList> {
    return $Call.ByID(996510192, id);
}

/**
 * DetectCLIAgents scans PATH (plus common toolchain dirs) for known coding
 * agents so the settings UI can list what is already installed.
 */
export function DetectCLIAgents(): $CancellablePromise<$models.CLIAgent[] | null> {
    return $Call.ByID(3315416933);
}

/**
 * FetchModels asks the provider for its model list via the OpenAI-compatible
 * /models endpoint, feeding the editor's suggestions.
 */
export function FetchModels(p: $models.AIProfile): $CancellablePromise<string[] | null> {
    return $Call.ByID(2371519422, p);
}

/**
 * GetConfig flattens the active profile into the legacy single-config shape;
 * tools only care whether a key exists.
 */
export function GetConfig(): $CancellablePromise<$models.AIConfig> {
    return $Call.ByID(2648340830);
}

/**
 * GetProfiles returns every saved profile plus the active one's ID.
 */
export function GetProfiles(): $CancellablePromise<$models.AIProfileList> {
    return $Call.ByID(156125234);
}

export function Providers(): $CancellablePromise<$models.AIProvider[] | null> {
    return $Call.ByID(1502272950);
}

/**
 * SaveProfile creates or updates a profile; the first one saved becomes active.
 */
export function SaveProfile(p: $models.AIProfile): $CancellablePromise<$models.AIProfileList> {
    return $Call.ByID(2707095810, p);
}

/**
 * SetActiveProfile marks which profile Chat uses.
 */
export function SetActiveProfile(id: string): $CancellablePromise<$models.AIProfileList> {
    return $Call.ByID(138962291, id);
}

/**
 * SetConfig writes through to the active profile (legacy single-config path).
 */
export function SetConfig(cfg: $models.AIConfig): $CancellablePromise<void> {
    return $Call.ByID(636408010, cfg);
}

/**
 * TestProfile fires a one-shot completion at a (possibly unsaved) profile and
 * reports the model and latency, so a bad key or URL surfaces here instead of
 * mid-conversation in an AI tool.
 */
export function TestProfile(p: $models.AIProfile): $CancellablePromise<string> {
    return $Call.ByID(3513701045, p);
}
