// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HashService computes checksums for text and for files. Files are streamed so
 * a multi-gigabyte input costs a fixed 1MB of memory rather than its own size.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Algorithms(): $CancellablePromise<string[] | null> {
    return $Call.ByID(32509772);
}

export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(47829800);
}

/**
 * EncodeFileBase64 returns a file's contents as base64, optionally wrapped as a
 * data URI. Guarded by the same size cap as ReadFileBytes so the bridge can't
 * be handed a gigabyte string.
 */
export function EncodeFileBase64(path: string, asDataURI: boolean, mime: string): $CancellablePromise<string> {
    return $Call.ByID(1244193097, path, asDataURI, mime);
}

/**
 * HashFiles streams each file once, feeding every requested algorithm from the
 * same read. `expect` may be empty; when set, each file is marked matched if
 * any of its digests equals it (case-insensitive, hex or base64).
 */
export function HashFiles(paths: string[] | null, algos: string[] | null, expect: string): $CancellablePromise<$models.FileHashResult[] | null> {
    return $Call.ByID(3961023553, paths, algos, expect);
}

/**
 * HashText digests a string with every requested algorithm in one pass over
 * the input per algorithm — cheap, since text is already in memory.
 */
export function HashText(text: string, algos: string[] | null): $CancellablePromise<$models.HashDigest[] | null> {
    return $Call.ByID(3589803949, text, algos);
}
