// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImageService: Pixel Lab tools — batch convert, batch compress, icon generation.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Anchors(): $CancellablePromise<string[] | null> {
    return $Call.ByID(60177869);
}

export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(2785753219);
}

/**
 * CompressBatch re-encodes images with quality presets high/medium/low,
 * keeping each file's original format.
 */
export function CompressBatch(inputs: string[] | null, outDir: string, quality: string): $CancellablePromise<$models.BatchResult | null> {
    return $Call.ByID(3976300875, inputs, outDir, quality);
}

/**
 * ConvertBatch converts each input into targetFormat inside outDir.
 */
export function ConvertBatch(inputs: string[] | null, outDir: string, targetFormat: string): $CancellablePromise<$models.BatchResult | null> {
    return $Call.ByID(3304852232, inputs, outDir, targetFormat);
}

/**
 * GenerateIcons renders the source image into standard app-icon sizes and
 * bundles ICO (Windows) plus ICNS (macOS) containers.
 */
export function GenerateIcons(input: string, outDir: string, sizes: number[] | null, makeICO: boolean, makeICNS: boolean): $CancellablePromise<$models.IconResult | null> {
    return $Call.ByID(1185544700, input, outDir, sizes, makeICO, makeICNS);
}

export function ProbeImages(paths: string[] | null): $CancellablePromise<$models.ImageInfo[] | null> {
    return $Call.ByID(3159419287, paths);
}

/**
 * ResizeBatch rescales each input. `format` may be empty to keep the original.
 */
export function ResizeBatch(inputs: string[] | null, outDir: string, mode: string, width: number, height: number, quality: number, format: string): $CancellablePromise<$models.BatchResult | null> {
    return $Call.ByID(878032591, inputs, outDir, mode, width, height, quality, format);
}

/**
 * Thumbnail returns a small JPEG preview of the image at path as a data
 * URL, for the out-tray. Sources above 8 MB are skipped — a tray of outputs
 * should never read gigabytes just to show a strip of thumbnails.
 */
export function Thumbnail(path: string, max: number): $CancellablePromise<string> {
    return $Call.ByID(2438843503, path, max);
}

/**
 * WatermarkBatch stamps a PNG watermark onto every input.
 * 
 * The watermark arrives as base64 PNG rather than a path so the front end can
 * render text with the webview's own fonts — Go has no CJK face to draw with,
 * and shipping one would bloat the binary for a feature the browser does well.
 * 
 * `scalePct` sizes the mark relative to the image's shorter side, so the same
 * settings look consistent across a batch of mixed dimensions.
 */
export function WatermarkBatch(inputs: string[] | null, outDir: string, markPNG: string, anchor: string, scalePct: number, opacity: number, marginPct: number, tile: boolean, quality: number): $CancellablePromise<$models.BatchResult | null> {
    return $Call.ByID(51305423, inputs, outDir, markPNG, anchor, scalePct, opacity, marginPct, tile, quality);
}
