// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AIConfig {
    "platform": string;
    "apiKey": string;
    "customUrl": string;
    "customModel": string;
}

/**
 * AIProfile is one saved provider configuration, laid out along the usual
 * OpenAI-compatible integration fields: base URL, API key, model. Users may
 * keep several (say, a work key and a personal key) and mark one as active.
 */
export interface AIProfile {
    "id": string;
    "name": string;
    "platform": string;
    "apiKey": string;
    "model": string;

    /**
     * Protocol base URL, e.g. "https://api.deepseek.com/v1". Empty means
     * "the built-in default for Platform"; /chat/completions is appended
     * when a request goes out.
     */
    "baseUrl": string;

    /**
     * Command is the local CLI invocation when Platform is "cli".
     * `{prompt}` and `{model}` are substituted; if `{prompt}` is absent the
     * conversation is written to stdin.
     */
    "command": string;

    /**
     * Deprecated: earlier builds stored the full completions URL here.
     * loadProfiles folds it into BaseURL on read; nothing writes it anymore.
     */
    "customUrl"?: string;
}

export interface AIProfileList {
    "profiles": AIProfile[] | null;
    "activeId": string;
}

export interface AIProvider {
    "id": string;
    "label": string;
    "baseUrl": string;
    "model": string;

    /**
     * NoKey is true for local OpenAI-compatible servers (Ollama, LM Studio)
     * that accept an empty or dummy bearer token.
     */
    "noKey": boolean;
}

export interface AIStreamChunk {
    "id": string;
    "delta": string;
    "done": boolean;
    "error"?: string;
}

export interface BatchResult {
    "successCount": number;
    "failCount": number;
    "outputDir": string;
    "errors": string[] | null;
    "originalSize"?: number;
    "compressedSize"?: number;
}

/**
 * CLIAgent is one coding-agent CLI the settings picker can offer, the same
 * "scan PATH, pick what you already have" shape OpenDesign uses.
 */
export interface CLIAgent {
    "id": string;
    "label": string;
    "tagline": string;
    "bin": string;
    "command": string;
    "installed": boolean;
    "path": string;
    "version": string;
    "installUrl": string;
}

export interface ChatMessage {
    "role": string;
    "content": string;
}

/**
 * CheckResult is what the frontend renders. When HasUpdate is false the other
 * fields are zero — the running build is already the latest release.
 */
export interface CheckResult {
    "hasUpdate": boolean;
    "currentVersion": string;
    "latestVersion": string;
    "releaseUrl": string;
    "notes": string;
    "artifactName": string;
}

export interface ConvertProgress {
    "fileName": string;
    "current": number;
    "total": number;
    "progress": number;

    /**
     * converting | done | error
     */
    "status": string;
}

export interface FileHashResult {
    "path": string;
    "name": string;
    "size": number;
    "digests": HashDigest[] | null;
    "error"?: string;

    /**
     * * Set when the caller supplied an expected value to compare against.
     */
    "matched": boolean;
    "compared": boolean;
}

export interface FileInfo {
    "path": string;
    "name": string;
    "size": number;
}

/**
 * FilesDropped is emitted to the frontend when files are dropped on the window.
 * Zone carries the data-file-drop-target value of the element they landed on.
 */
export interface FilesDropped {
    "zone": string;
    "files": FileInfo[] | null;
}

export interface HashDigest {
    "algo": string;
    "hex": string;
    "base64": string;
}

export interface HistoryItem {
    "id": number;
    "tool": string;
    "detail": string;
    "createdAt": string;
}

export interface IconResult {
    "success": boolean;
    "outputDir": string;
    "files": string[] | null;
    "error"?: string;
}

/**
 * ProbeImage reports an image's pixel dimensions without decoding the pixels.
 */
export interface ImageInfo {
    "path": string;
    "width": number;
    "height": number;
    "format": string;
    "error"?: string;
}

export interface PDFResult {
    "success": boolean;
    "outputPath": string;
    "outputDir": string;
    "outputFiles": string[] | null;
    "error"?: string;
    "inputSize"?: number;
    "outputSize"?: number;
}

export interface QRDecoded {
    "path": string;
    "name": string;
    "text": string;
    "format": string;
    "error"?: string;
}

export interface QRResult {
    /**
     * * PNG bytes as base64, for previewing without touching disk.
     */
    "dataUri": string;
    "size": number;
    "error"?: string;
}

export interface RenamePlan {
    "items": RenamePlanItem[] | null;
    "conflicts": number;
    "changed": number;
    "error"?: string;
}

export interface RenamePlanItem {
    "path": string;
    "oldName": string;
    "newName": string;

    /**
     * * Set when this row cannot be applied — the UI shows it and Run stays off.
     */
    "problem"?: string;
    "changed": boolean;
}

export interface RenameResult {
    "renamed": number;
    "failed": number;
    "errors": string[] | null;
}

/**
 * RenameRule describes the transformation. Steps apply in field order:
 * find/replace, then case, then prefix/suffix, then numbering, then extension.
 */
export interface RenameRule {
    "find": string;
    "replace": string;

    /**
     * * Treat Find as a regular expression rather than literal text.
     */
    "regex": boolean;
    "caseSensitive": boolean;
    "prefix": string;
    "suffix": string;

    /**
     * * "", "upper", "lower", "title" — applied to the stem only.
     */
    "caseMode": string;

    /**
     * * When true, append a running number; {n} in prefix/suffix is replaced too.
     */
    "numbering": boolean;
    "startAt": number;
    "padding": number;

    /**
     * * Replacement extension without the dot; empty keeps the original.
     */
    "extension": string;
}
