// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PDFService implements the Document Studio tools on top of pdfcpu.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Compress rewrites the PDF through pdfcpu's optimizer.
 */
export function Compress(input: string, outDir: string): $CancellablePromise<$models.PDFResult | null> {
    return $Call.ByID(555517190, input, outDir);
}

/**
 * Decrypt removes the password of a protected PDF.
 */
export function Decrypt(input: string, outDir: string, password: string): $CancellablePromise<$models.PDFResult | null> {
    return $Call.ByID(3707089435, input, outDir, password);
}

/**
 * Encrypt protects a PDF with a user (open) password. AES-256 by default.
 */
export function Encrypt(input: string, outDir: string, userPw: string, ownerPw: string): $CancellablePromise<$models.PDFResult | null> {
    return $Call.ByID(139364887, input, outDir, userPw, ownerPw);
}

/**
 * FromImages builds a PDF whose pages each carry one image.
 * 
 * `pageSize` is a pdfcpu paper name (A4, Letter, …) or "auto" to make each
 * page exactly the image's own size — the right default for scans and
 * screenshots, where letterboxing onto A4 would only add noise.
 */
export function FromImages(inputs: string[] | null, outDir: string, pageSize: string, landscape: boolean): $CancellablePromise<$models.PDFResult | null> {
    return $Call.ByID(1692137684, inputs, outDir, pageSize, landscape);
}

/**
 * Merge joins inputs (in order) into one PDF inside outDir.
 */
export function Merge(inputs: string[] | null, outDir: string): $CancellablePromise<$models.PDFResult | null> {
    return $Call.ByID(4096138798, inputs, outDir);
}

/**
 * PageCount returns the number of pages in a PDF.
 */
export function PageCount(input: string): $CancellablePromise<number> {
    return $Call.ByID(2646655732, input);
}

/**
 * PageSizes lists the paper names the UI may offer, "auto" first.
 */
export function PageSizes(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2839857661);
}

/**
 * Rotate turns pages by degrees (90/180/270). pages "" means all pages.
 */
export function Rotate(input: string, outDir: string, degrees: number, pages: string): $CancellablePromise<$models.PDFResult | null> {
    return $Call.ByID(3554203485, input, outDir, degrees, pages);
}

/**
 * Split cuts a PDF. mode "each" = one file per page, "span" = every N pages,
 * "range" = extract the given page selection (e.g. "1-3,7") into one file.
 */
export function Split(input: string, outDir: string, mode: string, span: number, pages: string): $CancellablePromise<$models.PDFResult | null> {
    return $Call.ByID(4142588950, input, outDir, mode, span, pages);
}
