// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QRService encodes and decodes QR codes. Both directions run locally — the
 * point of a local toolbox is that a payload with a password in it never
 * leaves the machine.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Decode reads codes out of image files. gozxing handles QR plus the common
 * 1D symbologies, so a scanned barcode works too.
 */
export function Decode(paths: string[] | null): $CancellablePromise<$models.QRDecoded[] | null> {
    return $Call.ByID(1933886199, paths);
}

/**
 * Encode renders text into a QR PNG and hands back a data URI. `logoPath` may
 * be empty; when set it is scaled to ~22% of the code and centred, which the
 * error correction absorbs at level "high" or better.
 */
export function Encode(text: string, size: number, level: string, fg: string, bg: string, logoPath: string): $CancellablePromise<$models.QRResult | null> {
    return $Call.ByID(2036282975, text, size, level, fg, bg, logoPath);
}

/**
 * EncodeToFile writes the QR straight to disk, for when the user wants a file
 * rather than something to copy.
 */
export function EncodeToFile(text: string, outDir: string, size: number, level: string, fg: string, bg: string, logoPath: string): $CancellablePromise<$models.PDFResult | null> {
    return $Call.ByID(4070719356, text, outDir, size, level, fg, bg, logoPath);
}

export function Levels(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2088258274);
}
