// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RenameService previews and applies batch renames.
 * 
 * This is the only service that mutates files the user already had, so it is
 * deliberately conservative: the plan is computed and returned first, every
 * collision is refused rather than resolved, and the apply pass renames
 * through temporary names so that swaps (a→b, b→a) work.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Apply executes a plan. It refuses outright if any row has a problem — a
 * partially applied batch rename is far harder to recover from than one that
 * never started.
 */
export function Apply(paths: string[] | null, rule: $models.RenameRule): $CancellablePromise<$models.RenameResult | null> {
    return $Call.ByID(614834364, paths, rule);
}

/**
 * Plan computes the new names without touching anything on disk.
 */
export function Plan(paths: string[] | null, rule: $models.RenameRule): $CancellablePromise<$models.RenamePlan | null> {
    return $Call.ByID(495766027, paths, rule);
}
