// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StoreService persists settings, favorites and usage history in SQLite.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddHistory records one tool usage; keeps the most recent 500 entries.
 */
export function AddHistory(tool: string, detail: string): $CancellablePromise<void> {
    return $Call.ByID(3672052000, tool, detail);
}

export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(3031506174);
}

export function GetAllSettings(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(3692075667);
}

export function GetFavorites(): $CancellablePromise<string[] | null> {
    return $Call.ByID(54496920);
}

export function GetHistory(limit: number): $CancellablePromise<$models.HistoryItem[] | null> {
    return $Call.ByID(1401670861, limit);
}

/**
 * GetSetting returns the stored value for key, or "" when unset.
 */
export function GetSetting(key: string): $CancellablePromise<string> {
    return $Call.ByID(3746079673, key);
}

/**
 * RemoveHistoryByTool drops every record of one tool, so the recently-used
 * row for it can be dismissed without touching the rest of the log.
 */
export function RemoveHistoryByTool(tool: string): $CancellablePromise<void> {
    return $Call.ByID(854411272, tool);
}

export function SetSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2882094125, key, value);
}

/**
 * ToggleFavorite flips the favorite state for a tool and returns the new state.
 */
export function ToggleFavorite(tool: string): $CancellablePromise<boolean> {
    return $Call.ByID(3617840497, tool);
}
