// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService exposes directories, dialogs, shell and file helpers.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DefaultOutputDir returns (and creates) ~/Documents/HiTool/<sub>.
 */
export function DefaultOutputDir(sub: string): $CancellablePromise<string> {
    return $Call.ByID(3235310024, sub);
}

export function GetDocumentsDir(): $CancellablePromise<string> {
    return $Call.ByID(603246620);
}

export function GetDownloadsDir(): $CancellablePromise<string> {
    return $Call.ByID(3993690317);
}

export function GetFileSize(path: string): $CancellablePromise<number> {
    return $Call.ByID(2834554954, path);
}

/**
 * GetVersion returns the build-time version ("dev" for local builds, the
 * tagged semver for release builds). The frontend compares it against the
 * latest GitHub release to offer updates.
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(2661091807);
}

export function OpenPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(4095270504, path);
}

export function OpenURL(raw: string): $CancellablePromise<void> {
    return $Call.ByID(2362861608, raw);
}

export function PathExists(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(1737866772, path);
}

/**
 * ReadFileBytes returns the raw content of a file (base64 across the bridge).
 */
export function ReadFileBytes(path: string): $CancellablePromise<string | null> {
    return $Call.ByID(2065089248, path);
}

export function RevealInFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(863362649, path);
}

/**
 * SaveFile opens a native save dialog; returns "" when cancelled.
 */
export function SaveFile(title: string, defaultName: string): $CancellablePromise<string> {
    return $Call.ByID(2793398264, title, defaultName);
}

/**
 * SelectDirectory opens a native directory picker; returns "" when cancelled.
 */
export function SelectDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(2257967314, title);
}

/**
 * SelectFiles opens a native multi/single file picker. Patterns look like "*.pdf".
 */
export function SelectFiles(title: string, filterName: string, patterns: string[] | null, multiple: boolean): $CancellablePromise<string[] | null> {
    return $Call.ByID(1243824090, title, filterName, patterns, multiple);
}

/**
 * StatFiles maps paths to name+size info, skipping unreadable entries.
 */
export function StatFiles(paths: string[] | null): $CancellablePromise<$models.FileInfo[] | null> {
    return $Call.ByID(1724247364, paths);
}

export function WriteFileBytes(path: string, data: string | null): $CancellablePromise<void> {
    return $Call.ByID(245231803, path, data);
}

/**
 * WriteFileChunk appends chunked data; offset 0 truncates first.
 */
export function WriteFileChunk(path: string, offset: number, data: string | null): $CancellablePromise<void> {
    return $Call.ByID(2785994253, path, offset, data);
}
