// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService bridges the Wails v3 updater (app.Updater) to the frontend.
 * It is registered as an application.Service after the app is created, so the
 * UI can drive Check / DownloadAndInstall through generated bindings and
 * subscribe to the wails:updater:* events for progress.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check asks the configured providers for a newer release. Returns a result
 * with HasUpdate=false when already up to date (no error).
 */
export function Check(): $CancellablePromise<$models.CheckResult | null> {
    return $Call.ByID(92632941);
}

/**
 * CurrentVersion returns the build-time version injected via -ldflags.
 */
export function CurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(4192472056);
}

/**
 * DownloadAndInstall streams the release selected by a previous Check,
 * verifies it, and stages it for the binary swap. The app must restart for
 * the new version to take effect — the frontend listens for the
 * wails:updater:update-ready event and prompts the user.
 */
export function DownloadAndInstall(): $CancellablePromise<void> {
    return $Call.ByID(746818923);
}

/**
 * Restart relaunches the application with the newly staged binary. The Wails
 * updater re-executes the running process in helper mode, which waits for the
 * current process to exit, swaps the on-disk binary, and relaunches — so this
 * call does not return (the process exits during the swap).
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(926581522);
}

/**
 * State reports the updater lifecycle phase (idle/checking/downloading/…).
 */
export function State(): $CancellablePromise<string> {
    return $Call.ByID(4008204924);
}
