<script setup lang="ts">
/**
 * SVG clean-up, with the result rendered beside the source.
 *
 * The preview goes through an `<img src="data:…">` rather than being inlined
 * into the page. SVG is a document format — inlining one from an unknown file
 * would run whatever it carries. Through an `<img>` it cannot, whether or not
 * the script-stripping switch is on.
 */
import { computed, ref } from "vue";
import ToolFrame from "../../work/ToolFrame.vue";
import InspectorSection from "../../work/InspectorSection.vue";
import Icon from "../../components/Icon.vue";
import { t } from "../../lib/i18n";
import { copyText, toast } from "../../stores/toast";
import { errText } from "../../lib/err";
import {
  formatBytes,
  inWails,
  outputDir,
  pickFiles,
  readFileBytes,
  writeFileChunked,
  baseName,
} from "../../lib/backend";
import { addOutput, finishJob, setProgress, startJob, type Job } from "../../stores/jobs";
import * as StoreService from "@bindings/hitool/services/storeservice";
import { onFilesDropped, dragActive, useFileHandoff } from "../../lib/drop";
import { decodeText, MAX_TEXT_BYTES } from "../../lib/textfile";
import { DEFAULT_OPTIONS, looksLikeSvg, optimise, toDataUri, type SvgOptions } from "../../lib/svgo";
import type { FileInfo } from "@bindings/hitool/services/models";

const SAMPLE = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by an editor -->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
     version="1.1" xml:space="preserve" width="48" height="48" viewBox="0 0 48 48">
  <metadata><rdf:RDF xmlns:rdf="http://x"/></metadata>
  <sodipodi:namedview id="base" pagecolor="#ffffff"/>
  <g id="" inkscape:label="Layer 1" class="">
    <circle cx="24.000000" cy="24.0000001" r="20.4999998" fill="#5457d6"/>
    <path d="M 14.2500001 24.3333333 L 21.6666667 31.7500000 L 33.7500000 16.2500000"
          stroke="#ffffff" stroke-width="3.00000001" fill="none"/>
  </g>
</svg>`;

const src = ref(SAMPLE);
const name = ref("");
const opts = ref<Required<SvgOptions>>({ ...DEFAULT_OPTIONS });
const exporting = ref(false);
const batch = ref<FileInfo[]>([]);
const busy = ref(false);
const job = ref<Job>();

const SWITCHES: (keyof SvgOptions)[] = [
  "comments",
  "scripts",
  "metadata",
  "editorNamespaces",
  "emptyAttributes",
  "collapseWhitespace",
  "responsive",
];

const valid = computed(() => !src.value.trim() || looksLikeSvg(src.value));
const result = computed(() => optimise(src.value, opts.value));
const preview = computed(() => (valid.value && src.value.trim() ? toDataUri(result.value.svg) : ""));
const cssUri = computed(() => `background-image: url("${toDataUri(result.value.svg)}");`);

function toggle(k: keyof SvgOptions) {
  opts.value = { ...opts.value, [k]: !opts.value[k] };
}

async function load(f: FileInfo) {
  if (f.size > MAX_TEXT_BYTES) {
    toast(t("diff.tooBig", { name: f.name, max: formatBytes(MAX_TEXT_BYTES) }), "fail");
    return;
  }
  try {
    const d = decodeText(await readFileBytes(f.path));
    if (d.binary || !looksLikeSvg(d.text)) {
      toast(t("svg.notSvg", { name: f.name }), "fail");
      return;
    }
    src.value = d.text;
    name.value = f.name;
  } catch (e) {
    toast(errText(e), "fail");
  }
}

function take(files: FileInfo[]) {
  if (files.length > 1) {
    batch.value = files;
    return;
  }
  batch.value = [];
  if (files[0]) load(files[0]);
}

onFilesDropped(take);
useFileHandoff(take);

async function choose() {
  const paths = await pickFiles(t("common.selectFiles"), "SVG", ["svg"], true);
  if (!paths.length) return;
  const { StatFiles } = await import("@bindings/hitool/services/systemservice");
  const stat = (await StatFiles(paths)) ?? [];
  if (stat.length) take(stat);
}

async function runBatch() {
  if (!batch.value.length || busy.value || !inWails()) return;
  busy.value = true;
  const dir = await outputDir("SVG");
  const j = startJob({
    tool: "svg-tool",
    label: `${t("tools.svg-tool.name")} · ${batch.value.length}`,
    total: batch.value.length,
    outputDir: dir,
  });
  job.value = j;
  try {
    for (let i = 0; i < batch.value.length; i++) {
      const f = batch.value[i];
      setProgress(j, i, batch.value.length, f.name);
      try {
        const source = new TextDecoder().decode(await readFileBytes(f.path));
        if (!looksLikeSvg(source)) {
          addOutput(j, { path: f.path, name: f.name, detail: t("svgb.notSvg"), ok: false });
          continue;
        }
        const res = optimise(source, opts.value);
        const outPath = `${dir}/${baseName(f.path).replace(/\.svg$/i, "")}_opt.svg`;
        await writeFileChunked(outPath, new TextEncoder().encode(res.svg));
        await StoreService.AddHistory("svg-tool", baseName(outPath)).catch(() => {});
        addOutput(j, {
          path: outPath,
          name: baseName(outPath),
          detail: t("svgb.saved", {
            before: formatBytes(res.before),
            after: formatBytes(res.after),
            pct: Math.round(res.saved * 100),
          }),
          ok: true,
        });
      } catch (e) {
        addOutput(j, { path: f.path, name: f.name, detail: errText(e), ok: false });
      }
    }
    setProgress(j, batch.value.length, batch.value.length);
    finishJob(j, "done");
  } catch (e) {
    finishJob(j, "failed", errText(e));
  } finally {
    busy.value = false;
  }
}

async function save() {
  if (exporting.value || !result.value.svg) return;
  if (!inWails()) {
    toast(t("svg.exportDesktopOnly"), "fail");
    return;
  }
  exporting.value = true;
  try {
    const dir = await outputDir("SVG");
    const stem = (name.value || "icon").replace(/\.svg$/i, "");
    const file = `${stem}.min.svg`;
    await writeFileChunked(`${dir}/${file}`, new TextEncoder().encode(result.value.svg));
    toast(t("svg.exported", { path: file }), "ok");
  } catch (e) {
    toast(errText(e), "fail");
  } finally {
    exporting.value = false;
  }
}
</script>

<template>
  <ToolFrame tool-id="svg-tool" shape="flow">
    <div v-if="batch.length" class="field">
      <div class="head">
        <span class="lab">{{ t("tools.svg-tool.name") }} · {{ batch.length }}</span>
        <button class="mini" :title="t('diff.openFile')" @click="choose"><Icon name="FolderOpen" /></button>
        <button class="chip" @click="batch = []">{{ t("common.clear") }}</button>
      </div>
      <ul class="batch">
        <li v-for="f in batch" :key="f.path" class="truncate">{{ f.name }}</li>
      </ul>
      <button class="btn btn-signal" :disabled="busy" @click="runBatch">
        {{ t("common.start") }}
      </button>
    </div>
    <div v-else class="field grow-field" :class="{ hot: dragActive }" data-file-drop-target="svg">
      <div class="head">
        <span class="lab">{{ t("svg.source") }}</span>
        <span v-if="name" class="fname truncate" :title="name">{{ name }}</span>
        <span v-if="src" class="lab">{{ formatBytes(result.before) }}</span>
        <button class="mini" :title="t('diff.openFile')" @click="choose">
          <Icon name="FolderOpen" />
        </button>
      </div>
      <textarea
        v-model="src"
        class="textarea mono doc"
        :class="{ bad: !valid }"
        :placeholder="t('svg.sourcePh')"
        spellcheck="false"
        @input="name = ''"
      ></textarea>
      <p v-if="!valid" class="err">{{ t("svg.notSvgText") }}</p>
    </div>

    <div v-if="!batch.length" class="row">
      <button class="btn btn-sm btn-quiet" :disabled="!src" @click="copyText(result.svg, t('common.copied'))">
        <Icon name="Copy" /> {{ t("svg.copySvg") }}
      </button>
      <button class="btn btn-sm btn-quiet" :disabled="!src" @click="copyText(cssUri, t('common.copied'))">
        {{ t("svg.copyCss") }}
      </button>
      <button class="btn btn-sm btn-quiet" @click="src = SAMPLE; name = ''">{{ t("svg.sample") }}</button>
      <span class="hint drophint">{{ t("svg.dropHint") }}</span>
    </div>

    <template v-if="!batch.length" #result>
      <div class="res-head">
        <span class="lab">{{ t("svg.result") }}</span>
        <template v-if="src && valid">
          <span class="badge" :class="result.saved > 0 ? 'ok' : ''">
            −{{ Math.round(result.saved * 100) }}%
          </span>
          <span class="lab mono">{{ formatBytes(result.before) }} → {{ formatBytes(result.after) }}</span>
        </template>
        <button class="btn btn-sm btn-quiet" :disabled="!result.svg || exporting" @click="save">
          <Icon name="Download" />
        </button>
      </div>

      <div class="stage">
        <div class="canvas">
          <!-- Through an <img>, so a document that carries a script cannot
               run it here regardless of the stripping switch. -->
          <img v-if="preview" :src="preview" class="art" :alt="t('svg.result')" />
          <p v-else class="hint">{{ t("svg.idle") }}</p>
        </div>
        <pre v-if="src && valid" class="out mono scroll-y">{{ result.svg }}</pre>
      </div>
    </template>

    <template #inspector>
      <InspectorSection :title="t('svg.clean')" icon="Sparkles" :open="true">
        <div class="chips">
          <button
            v-for="k in SWITCHES"
            :key="k"
            class="chip"
            :class="{ on: opts[k] }"
            @click="toggle(k)"
          >
            {{ t(`svg.o_${k}`) }}
          </button>
        </div>
        <p class="hint">{{ t("svg.responsiveHint") }}</p>
      </InspectorSection>

      <InspectorSection :title="t('svg.precision')" icon="SlidersHorizontal" :open="true">
        <input v-model.number="opts.precision" type="range" min="-1" max="6" step="1" class="slider" />
        <div class="thline">
          <span class="mono">{{ opts.precision < 0 ? t("svg.pKeep") : opts.precision }}</span>
          <span class="hint">{{ t("svg.pHint") }}</span>
        </div>
      </InspectorSection>

      <InspectorSection :title="t('svg.about')" icon="Info">
        <p class="hint">{{ t("svg.aboutSafe") }}</p>
        <p class="hint">{{ t("svg.aboutScripts") }}</p>
      </InspectorSection>
    </template>
  </ToolFrame>
</template>

<style scoped>
.grow-field {
  flex: 1;
  min-height: 0;
  border-radius: var(--r);
  transition: box-shadow 0.14s;
}

.grow-field.hot {
  box-shadow: 0 0 0 2px var(--acc);
}

.head {
  display: flex;
  align-items: center;
  gap: 8px;
}
.batch {
  margin: 0;
  padding: 8px 12px;
  border-radius: var(--r-sm);
  background: var(--s-2);
  max-height: 240px;
  overflow: auto;
  font-size: var(--t-sm);
  color: var(--ink-2);
}

.fname {
  flex: 1;
  min-width: 0;
  font-size: var(--t-xs);
  color: var(--ink-3);
  font-family: var(--f-mono);
}

.mini {
  margin-left: auto;
  width: 20px;
  height: 20px;
  display: grid;
  place-items: center;
  border: 0;
  border-radius: var(--r-sm);
  background: transparent;
  color: var(--ink-3);
  cursor: pointer;
}

.mini:hover {
  background: var(--s-3);
  color: var(--ink);
}

.mini :deep(svg) {
  width: 13px;
  height: 13px;
}

.doc {
  flex: 1;
  min-height: 220px;
}

.textarea.bad {
  border-color: var(--fail);
}

.err {
  font-size: var(--t-xs);
  color: var(--fail);
  margin-top: 4px;
}

.row {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
  align-items: center;
}

.drophint {
  margin-left: auto;
}

.res-head {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 11px 14px;
  border-bottom: 1px solid var(--line);
  flex-shrink: 0;
}

.res-head .btn {
  margin-left: auto;
}

.stage {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-height: 0;
}

.canvas {
  flex: 1;
  min-height: 140px;
  display: grid;
  place-items: center;
  padding: 16px;
  /* Chequerboard: an icon is usually transparent, and a white background
     would hide a white shape entirely. */
  background-image: linear-gradient(45deg, var(--s-3) 25%, transparent 25%),
    linear-gradient(-45deg, var(--s-3) 25%, transparent 25%),
    linear-gradient(45deg, transparent 75%, var(--s-3) 75%),
    linear-gradient(-45deg, transparent 75%, var(--s-3) 75%);
  background-size: 14px 14px;
  background-position: 0 0, 0 7px, 7px -7px, -7px 0;
}

.art {
  max-width: 100%;
  max-height: 220px;
}

.out {
  flex: 1;
  min-height: 0;
  margin: 0;
  padding: 12px 14px;
  border-top: 1px solid var(--line);
  font-size: var(--t-sm);
  line-height: 1.65;
  white-space: pre-wrap;
  word-break: break-all;
  user-select: text;
  color: var(--ink-2);
}

.chips {
  display: flex;
  flex-wrap: wrap;
  gap: 5px;
}

.thline {
  display: flex;
  align-items: baseline;
  gap: 8px;
  margin-top: 4px;
}
</style>
